# syntax=docker/dockerfile:1
ARG PYTHON_VERSION=3.12
ARG POETRY_VERSION=2.3.2

################################ Stage: venv-builder (prepare the virtualenv)
FROM python:${PYTHON_VERSION}-alpine AS venv-builder
ARG POETRY_VERSION

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 \
    PIP_CACHE_DIR="/.cache" \
    POETRY_CACHE_DIR="/.poetry-cache" \
    POETRY_HOME="/opt/poetry" \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    POETRY_VIRTUALENVS_PREFER_ACTIVE_PYTHON=true \
    PATH="/opt/poetry/bin:$PATH"

RUN apk add --no-cache \
    build-base \
    git \
    linux-headers \
    python3-dev \
    pcre2-dev

ADD https://install.python-poetry.org /tmp/install-poetry.py
RUN python /tmp/install-poetry.py

WORKDIR /label-studio

ENV VENV_PATH="/label-studio/.venv"
ENV PATH="$VENV_PATH/bin:$PATH"

COPY pyproject.toml poetry.lock README.md ./

RUN --mount=type=cache,target=/.poetry-cache,id=poetry-cache-alpine,sharing=locked \
    poetry check --lock && \
    poetry install --no-root --without test --extras uwsgi

COPY label_studio label_studio
RUN --mount=type=cache,target=/.poetry-cache,id=poetry-cache-alpine,sharing=locked \
    poetry install --only-root --extras uwsgi && \
    python3 label_studio/manage.py collectstatic --no-input

################################ Stage: production
FROM python:${PYTHON_VERSION}-alpine AS production

ENV LS_DIR=/label-studio \
    HOME=/label-studio \
    LABEL_STUDIO_BASE_DATA_DIR=/label-studio/data \
    OPT_DIR=/opt/heartex/instance-data/etc \
    PATH="/label-studio/.venv/bin:$PATH" \
    DJANGO_SETTINGS_MODULE=core.settings.label_studio \
    DJANGO_DB=postgresql \
    SKIP_DB_MIGRATIONS=true \
    LOG_DIR=/label-studio/data/logs \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

WORKDIR $LS_DIR

RUN apk add --no-cache \
    expat \
    mesa-gl \
    glib \
    curl \
    nginx \
    bash \
    procps

RUN set -eux; \
    mkdir -p $LS_DIR $LABEL_STUDIO_BASE_DATA_DIR $OPT_DIR $LOG_DIR && \
    chown -R 1001:0 $LS_DIR $LABEL_STUDIO_BASE_DATA_DIR $OPT_DIR $LOG_DIR /var/log/nginx /etc/nginx

COPY --chown=1001:0 deploy/default.conf /etc/nginx/nginx.conf
COPY --chown=1001:0 pyproject.toml .
COPY --chown=1001:0 poetry.lock .
COPY --chown=1001:0 README.md .
COPY --chown=1001:0 LICENSE LICENSE
COPY --chown=1001:0 licenses licenses
COPY --chown=1001:0 deploy deploy

COPY --chown=1001:0 --from=venv-builder /label-studio /label-studio

USER 1001

EXPOSE 8080

ENTRYPOINT ["./deploy/docker-entrypoint.sh"]
CMD ["label-studio"]
